### ISSUE TITLE
Always creates 3D coordinates

### ISSUE THREAD

**Issue by mxcolin** [NetTopologySuite/NetTopologySuite.IO.Oracle#11]
The OracleGeometryReader always creates the 3D CoordinateZ type even for 2D Coodinates.

It uses

`pts.Add(new CoordinateZ(ordinates[offset], ordinates[offset + 1], double.NaN));`

Which, would be fine if the writer accounted for that but it doesn't when writing the ordinates array, instead it just uses the sequence.Dimension property of the CoordinateSequence which will always be 3 based on the above. If you add this Test to your Tests you will see the behavior:

```
[TestCase]
public void ReadAndWrite()
{
    var geom1 = wr.Read("POLYGON((10 10,20 10,20 20,10 20,10 10))");
    var sdo = new OracleGeometryWriter().Write(geom1);
    var geom2 = or.Read(sdo);

    Assert.AreEqual(geom1.Coordinates[0].GetType(), geom2.Coordinates[1].GetType());
}
```

```
Message: 
  Expected: <NetTopologySuite.Geometries.Coordinate>
  But was:  <NetTopologySuite.Geometries.CoordinateZ>
```

What this means is that if you read a Geometry from the Database to a variable then attempt to add that Geometry back in it will error out with a:

`ORA-01400 cannot insert NULL into SPATIAL COLUMN error`

You can get around this by re-constituting the Geometry column from the returned text and SRID, but not ideal.

**Comment by umuretken** [comment]
I am experiencing the same problem.
Any progress on its solution?

**Comment by hlaebe** [comment]
Ran into this today. IMHO the OracleGeometryWriter is the problem, the definition of the dimension is inconsistent. I fixed it and created a PR. It helped me, hopefully helps you too.
