### ISSUE TITLE
Support other .NET Standard targets

### ISSUE THREAD

**Issue by airbreather** [NetTopologySuite/NetTopologySuite.IO.Oracle#3]
[`Oracle.ManagedDataAccess.Core`](https://www.nuget.org/packages/Oracle.ManagedDataAccess.Core) is a `netstandard2.0` package.

At the time of writing, however, this library [does not support UDT mapping](https://docs.oracle.com/cd/E85694_01/ODPNT/featUDTs.htm#ODPNT379), which we use heavily.

**Comment by mathijs-dumon** [comment]
It seems a recent version has now support for UDT mapping:
https://medium.com/oracledevs/announcing-odp-net-21-3-user-defined-types-for-managed-odp-net-and-odp-net-core-836fa81da3ba

they even have a code sample for spatial types:
https://github.com/oracle/dotnet-db-samples/blob/master/samples/udt/Spatial-UDT.cs

**Comment by FObermaier** [comment]
Fixed with 7a6535983eeca4291b70f4878cf55baf72264433
