### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by FObermaier** [NetTopologySuite/NetTopologySuite.IO.Oracle#8]
Thanks to the work of @mathijs-dumon and his colleagues this IO package is ready for a new release, I think.
Since we have substituted some of the dependencies and made significant changes to `SdoGeometry` and `SdoPoint` a new release should carry the version v3.0.

@airbreather do you agree?
@mathijs-dumon, could have a look at the [ReadMe](https://github.com/NetTopologySuite/NetTopologySuite.IO.Oracle#readme)?

**Comment by mathijs-dumon** [comment]
@FObermaier I added a more complete example in a PR, feel free to adapt further. We struggled a bit with the parameter binding initially, so could be useful to others.

Otherwise great to see this moving forward so quickly!

**Comment by FObermaier** [comment]
Released 1597c178bf2ff57264c0b32fb26de8f9b1f5eca8
